version: '3.8'
services:

  mariadb:
    image: mariadb:10.5.8
    ports: [ '3306:3306' ]
    env_file: [ ./etc/.env ]
    volumes:
      - ./var/mariadb:/var/lib/mysql
      #- ./etc/mariadb:/etc/mysql/conf.d
