name: Manual Test

on:
  workflow_dispatch:
      inputs:
        target_branch:
          description: 'Branch to run the workflow on'
          required: true
          default: 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Manual trigger works!"
